import 'package:athar_app/core/models/chat/chat_session_model.dart';
import 'package:athar_app/core/models/chat/region_model.dart';
import 'package:athar_app/features/cultural_archive/logic/cultural_notifier.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../logic/chat_repository.dart';
import '../../../../services/gemini_service.dart';
import 'package:athar_app/core/models/chat/chat_message_model.dart';
import 'package:athar_app/features/cultural_archive/logic/cultural_repository.dart';
import 'package:athar_app/features/auth/logic/auth_repository.dart';
import 'package:athar_app/core/providers/settings_provider.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'dart:typed_data';
part 'chat_notifier.g.dart';

dynamic _convertResponse(dynamic data) {
  if (data is Map) {
    return Map<String, dynamic>.fromEntries(
      data.entries.map((e) => MapEntry(e.key.toString(), _convertResponse(e.value))),
    );
  }
  if (data is List) {
    return data.map(_convertResponse).toList();
  }
  return data;
}

@riverpod
class ChatNotifier extends _$ChatNotifier {
  @override
  bool build() => false;

  bool _containsArabic(String value) {
    final arabicRegex = RegExp(r'[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF]');
    return arabicRegex.hasMatch(value);
  }

  String _snippet(String text) {
    final normalized = text.replaceAll(RegExp(r'\s+'), ' ').trim();
    if (normalized.isEmpty) {
      return '';
    }
    if (normalized.length <= 42) {
      return normalized;
    }
    return '${normalized.substring(0, 42)}...';
  }

  bool _isGenericTitle(String title, {required bool isArabic}) {
    final normalized = title.trim().toLowerCase();
    if (normalized.isEmpty) {
      return true;
    }
    final genericArabic = <String>['سالفة عن', 'سالفة جديدة', 'محادثة جديدة'];
    final genericEnglish = <String>['story about', 'new chat'];
    final generic = isArabic ? genericArabic : genericEnglish;
    return generic.any((prefix) => normalized.startsWith(prefix));
  }

  ({String titleAr, String titleEn}) _buildMeaningfulTitles({
    required String userText,
    RegionModel? region,
  }) {
    final summary = _snippet(userText);
    final isArabicInput = _containsArabic(userText);
    final summaryAr = isArabicInput ? summary : '';
    final summaryEn = isArabicInput ? '' : summary;
    final arBase = region != null ? region.nameAr : 'المجلس العام';
    final enBase = region != null ? region.nameEn : 'General Council';

    if (summaryAr.isEmpty && summaryEn.isEmpty) {
      return (
        titleAr: 'سالفة عن $arBase',
        titleEn: 'Story about $enBase',
      );
    }

    return (
      titleAr:
          summaryAr.isNotEmpty ? '$arBase: $summaryAr' : 'سالفة عن $arBase',
      titleEn:
          summaryEn.isNotEmpty ? '$enBase: $summaryEn' : 'Story about $enBase',
    );
  }

  bool _looksAutoGeneratedTitle({
    required String title,
    required bool isArabic,
    RegionModel? region,
  }) {
    final normalized = title.trim().toLowerCase();
    if (normalized.isEmpty) {
      return true;
    }

    if (_isGenericTitle(title, isArabic: isArabic)) {
      return true;
    }

    final prefix = isArabic
        ? (region != null ? '${region.nameAr}:'.toLowerCase() : 'المجلس العام:')
        : (region != null
            ? '${region.nameEn}:'.toLowerCase()
            : 'general council:');
    return normalized.startsWith(prefix);
  }

  String _buildTitlePrompt({
    required String language,
    required String regionName,
    required String conversation,
  }) {
    return '''
Create one short chat title in $language.
Context region: $regionName
Conversation:
$conversation

Rules:
- 3 to 6 words.
- Concrete and specific.
- No quotes, no emojis, no punctuation at start/end.
- Return title only.
''';
  }

  Future<void> _maybeRefineSessionTitle({
    required String userId,
    required String sessionId,
    required ChatRepository repository,
    required GeminiService gemini,
    RegionModel? region,
  }) async {
    final session = await repository.getSession(userId, sessionId);
    if (session == null) {
      return;
    }

    final shouldRefineArabic = _looksAutoGeneratedTitle(
      title: session.titleAr,
      isArabic: true,
      region: region,
    );
    final shouldRefineEnglish = _looksAutoGeneratedTitle(
      title: session.titleEn,
      isArabic: false,
      region: region,
    );

    if (!shouldRefineArabic && !shouldRefineEnglish) {
      return;
    }

    final recent =
        await repository.getRecentMessages(userId, sessionId, limit: 8);
    if (recent.isEmpty) {
      return;
    }

    final userMessagesCount = recent.where((m) => m.isUser).length;
    if (userMessagesCount < 2) {
      return;
    }

    final ordered = recent.reversed.toList();
    final conversation = ordered
        .map((m) => '${m.isUser ? 'User' : 'Assistant'}: ${m.text}')
        .join('\n');

    String? refinedAr;
    String? refinedEn;

    try {
      if (shouldRefineArabic) {
        refinedAr = await gemini.getResponse(
          prompt: _buildTitlePrompt(
            language: 'Arabic',
            regionName: region?.nameAr ?? 'المجلس العام',
            conversation: conversation,
          ),
          systemInstruction:
              'You are a title generator. Return only one concise Arabic title.',
        );
      }

      if (shouldRefineEnglish) {
        refinedEn = await gemini.getResponse(
          prompt: _buildTitlePrompt(
            language: 'English',
            regionName: region?.nameEn ?? 'General Council',
            conversation: conversation,
          ),
          systemInstruction:
              'You are a title generator. Return only one concise English title.',
        );
      }
    } catch (_) {
      // Non-blocking enhancement: keep existing title if refinement fails.
      return;
    }

    final cleanAr = refinedAr?.replaceAll(RegExp(r'\s+'), ' ').trim();
    final cleanEn = refinedEn?.replaceAll(RegExp(r'\s+'), ' ').trim();

    if ((cleanAr == null || cleanAr.isEmpty) &&
        (cleanEn == null || cleanEn.isEmpty)) {
      return;
    }

    await repository.updateSessionTitles(
      userId,
      sessionId,
      titleAr: (cleanAr != null && cleanAr.isNotEmpty) ? cleanAr : null,
      titleEn: (cleanEn != null && cleanEn.isNotEmpty) ? cleanEn : null,
      legacyTitle: (cleanAr != null && cleanAr.isNotEmpty)
          ? cleanAr
          : ((cleanEn != null && cleanEn.isNotEmpty) ? cleanEn : null),
      lastMessageTime: DateTime.now(),
    );
  }

  // Task 4: Greeting Logic
  Future<void> sendInitialGreeting({
    required RegionModel region,
    required String sessionId,
  }) async {
    state = true;
    try {
      final authRepo = ref.read(authRepositoryProvider);
      final userId = authRepo.currentUser?.uid ?? 'guest_user';
      final repository = ref.read(chatRepositoryProvider);
      final gemini = ref.read(geminiServiceProvider);
      final settings = ref.read(settingsProvider); //  read settings
      final langCode = settings.locale.languageCode; //  get language

      final newSession = ChatSessionModel(
        sessionId: sessionId,
        regionId: region.regionId,
        titleAr: "سالفة عن ${region.nameAr}",
        titleEn: "Story about ${region.nameEn}",
        lastMessageTime: DateTime.now(),
      );
      await repository.createSession(userId, newSession);

      final String systemInstruction = '''
        ${region.systemPrompt}

        --- RUNTIME INPUTS ---
        isFirstTurn: true
        itemsNames: []
        userLanguage: $langCode
        ''';
      final response = await gemini.getResponse(
        prompt: "Begin.",
        systemInstruction: systemInstruction,
      );

      // Stop typing indicator before the final bot message is rendered.
      state = false;

      final botMessage = ChatMessageModel(
        text: response,
        senderId: 'bot',
        isUser: false,
        timestamp: DateTime.now(),
      );
      await repository.saveMessage(userId, sessionId, botMessage);
    } catch (e) {
      print("Error in Initial Greeting: $e");
    } finally {
      state = false;
    }
  }

  Future<void> sendUserMessage({
    RegionModel? region,
    required String text,
    required String sessionId,
    Uint8List? imageBytes,
  }) async {
    state = true;
    try {
      final cleanText = text.trim();
      if (cleanText.isEmpty) return;

      final authRepo = ref.read(authRepositoryProvider);
      final userId = authRepo.currentUser?.uid ?? 'guest_user';
      final settings = ref.read(settingsProvider);
      final langCode = settings.locale.languageCode;
      final effectiveLangCode = _containsArabic(cleanText) ? 'ar' : langCode;
      final repository = ref.read(chatRepositoryProvider);
      final gemini = ref.read(geminiServiceProvider);
      final now = DateTime.now();

      // 1. التعامل مع الجلسة (Session Logic)
      final session = await repository.getSession(userId, sessionId);
      final generatedTitles =
          _buildMeaningfulTitles(userText: cleanText, region: region);

      if (session == null) {
        await repository.createSession(
          userId,
          ChatSessionModel(
            sessionId: sessionId,
            regionId: region?.regionId ?? 'general',
            titleAr: generatedTitles.titleAr,
            titleEn: generatedTitles.titleEn,
            lastMessageTime: now,
          ),
        );
      } else {
        await repository.upsertSession(
          userId,
          ChatSessionModel(
            sessionId: session.sessionId,
            regionId: session.regionId.isNotEmpty
                ? session.regionId
                : (region?.regionId ?? 'general'),
            titleAr: session.titleAr.isNotEmpty &&
                    !_isGenericTitle(session.titleAr, isArabic: true)
                ? session.titleAr
                : generatedTitles.titleAr,
            titleEn: session.titleEn.isNotEmpty &&
                    !_isGenericTitle(session.titleEn, isArabic: false)
                ? session.titleEn
                : generatedTitles.titleEn,
            title: session.title,
            lastMessageTime: now,
          ),
        );
      }

      // 2. جلب سياق المحادثة مرة واحدة فقط (Memory Context)
      // استخدمنا حد 10 رسائل لتعزيز الذاكرة
      final recentMessages =
          await repository.getRecentMessages(userId, sessionId, limit: 10);
      
      final isAr = effectiveLangCode == 'ar';
      final userLabel = isAr ? "المستخدم" : "User";
      final botLabel = isAr ? "راوي" : "Rawi";
      final historyHeader = isAr ? "سياق المحادثة السابق:" : "Previous Conversation History:";
      
      final historyContext = recentMessages.reversed
        .map((m) => '${m.isUser ? userLabel : botLabel}: ${m.text}')
        .join('\n');


      final fullPrompt = '''
      $historyHeader
      $historyContext

      $userLabel: $cleanText
      ''';

      // 3. بناء التعليمات البرمجية (System Instruction)
      String systemInstruction = '';
      if (region != null) {
        var regionalItems = ref
            .read(culturalNotifierProvider.notifier)
            .getItemsByRegion(region.regionId);

        if (regionalItems.isEmpty) {
          final culturalRepo = ref.read(culturalRepositoryProvider);
          final allItems = await culturalRepo.fetchItems();
          regionalItems = allItems
              .where((item) => item.regionId == region.regionId)
              .toList();
        }

        final itemsTitles = regionalItems
            .map((e) => effectiveLangCode == 'ar' ? e.titleAr : e.titleEn)
            .join('، ');

        systemInstruction = '''
${region.systemPrompt}

--- RUNTIME INPUTS ---
isFirstTurn: false
itemsNames: [$itemsTitles]
userLanguage: $effectiveLangCode
STRICT RULE: Your response MUST be in the same language as "Current User Message" ($effectiveLangCode).
''';
      } else {
        systemInstruction =
            'أنت "راوي"، مساعد ثقافي سعودي عام. أجب بلغة المستخدم وكن ودوداً.';
      }

      // 4. حفظ رسالة المستخدم أولاً
      await repository.saveMessage(
          userId,
          sessionId,
          ChatMessageModel(
              text: cleanText, senderId: userId, isUser: true, timestamp: now));

      // 5. استدعاء askRawi Cloud Function (RAG)
      String botReply;
      List<Map<String, dynamic>>? suggestedItems;

      if (imageBytes != null) {
        // Image messages fall back to direct Gemini (askRawi is text-only)
        botReply = await gemini.getResponse(
          prompt: fullPrompt,
          systemInstruction: systemInstruction,
          imageBytes: imageBytes,
        );
      } else {
        final callable = FirebaseFunctions.instance.httpsCallable('askRawi');
        final rawResult = await callable.call({
          'conversationId': sessionId,
          'userMessage': cleanText,
          'recentMessages': recentMessages.reversed
              .map((m) => {'role': m.isUser ? 'user' : 'assistant', 'content': m.text})
              .toList(),
          'locale': effectiveLangCode,
        });
        final converted = _convertResponse(rawResult.data) as Map<String, dynamic>;
        botReply = (converted['reply'] as String?)?.trim() ?? '';
        final rawItems = converted['suggestedItems'];
        if (rawItems is List && rawItems.isNotEmpty) {
          suggestedItems = rawItems
              .whereType<Map<String, dynamic>>()
              .toList();
        }
      }

      // Stop typing indicator before the final bot message is rendered.
      state = false;

      // 6. حفظ رد البوت
      await repository.saveMessage(
          userId,
          sessionId,
          ChatMessageModel(
              text: botReply,
              senderId: 'bot',
              isUser: false,
              suggestedItems: suggestedItems,
              timestamp: DateTime.now()));

      // 7. تحسين العنوان إذا لزم الأمر
      await _maybeRefineSessionTitle(
        userId: userId,
        sessionId: sessionId,
        repository: repository,
        gemini: gemini,
        region: region,
      );
    } finally {
      state = false;
    }
  }
}
